apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "azure-ad-monitor.fullname" . }}
  labels:
    {{- include "azure-ad-monitor.labels" . | nindent 4 }}
spec:
  endpoints:
    - port: http
      interval: 60s
      path: /metrics
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "azure-ad-monitor.selectorLabels" . | nindent 6 }}
